apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - conf.yaml

resources:
  - deploy.yaml
  - service.yaml
  - gateway.yaml
  - virtual-service.yaml

vars:
  - name: DOMAIN
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: kubecraft
    fieldref:
      fieldpath: metadata.annotations.domain
