apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base

namespace: kubecraft
resources:
  - ns.yaml
  - pv.yaml

configMapGenerator:
  - name: kubecraft
    files:
      - server.properties

patchesStrategicMerge:
  - patch.yaml
