apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mc-awes-one
spec:
  capacity:
    storage: 10Gi
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: ""
  claimRef:
    namespace: kubecraft
    name: pvc-mc
  mountOptions:
    - hard
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: pv-mc-awes-one
    volumeAttributes:
      server: 192.168.1.51
      share: /var/nfs/k8s/mc.awes.one